import { useBlockchain } from '@/stores';
import numeral from 'numeral';

const chainStore = useBlockchain()

const themeColors = (theme: string) => {
  if (theme === 'light') {
    return {
      dark: false,
      colors: {
        background: '#F1FDF6',
        surface: '#FFFFFF',
        'surface-variant': '#D4F8E8',
        'on-surface-variant': '#A7D9C5',
        primary: chainStore.current?.themeColor || '#4CAF50', // Light green primary
        'primary-darken-1': '#388E3C',
        secondary: '#81C784', // Secondary green
        'secondary-darken-1': '#66BB6A',
        error: '#E57373',
        info: '#64B5F6',
        success: '#4CAF50',
        warning: '#FFB74D',
        'on-primary': '#FFFFFF',
        'on-secondary': '#FFFFFF',
        'on-success': '#FFFFFF',
        'on-info': '#FFFFFF',
        'on-warning': '#FFFFFF',
        'on-background': '#2E7D32',
        'on-surface': '#2E7D32',
        'perfect-scrollbar-thumb': '#C8E6C9',
        'snackbar-background': '#F1FDF6',
        'tooltip-background': '#A5D6A7',
        'alert-background': '#D4F8E8',
        'grey-50': '#E8F5E9',
        'grey-100': '#C8E6C9',
        'grey-200': '#A5D6A7',
        'grey-300': '#81C784',
        'grey-400': '#66BB6A',
        'grey-500': '#4CAF50',
        'grey-600': '#43A047',
        'grey-700': '#388E3C',
        'grey-800': '#2E7D32',
        'grey-900': '#1B5E20',
        'on-primary-darken-1': '#FFFFFF',
        'on-secondary-darken-1': '#FFFFFF',
        'on-error': '#FFFFFF',
        'on-perfect-scrollbar-thumb': '#000000',
        'on-snackbar-background': '#000000',
        'on-tooltip-background': '#FFFFFF',
        'on-alert-background': '#000000',
        'on-grey-50': '#000000',
        'on-grey-100': '#000000',
        'on-grey-200': '#000000',
        'on-grey-300': '#000000',
        'on-grey-400': '#FFFFFF',
        'on-grey-500': '#FFFFFF',
        'on-grey-600': '#FFFFFF',
        'on-grey-700': '#FFFFFF',
        'on-grey-800': '#FFFFFF',
        'on-grey-900': '#FFFFFF',
      },
      variables: {
        'border-color': '#A7D9C5',
        'border-opacity': 0.12,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.6,
        'disabled-opacity': 0.38,
        'idle-opacity': 0.04,
        'hover-opacity': 0.05,
        'focus-opacity': 0.12,
        'selected-opacity': 0.08,
        'activated-opacity': 0.12,
        'pressed-opacity': 0.12,
        'dragged-opacity': 0.08,
        'theme-kbd': '#388E3C',
        'theme-on-kbd': '#FFFFFF',
        'theme-code': '#F1FDF6',
        'theme-on-code': '#000000',
        'code-color': '#4CAF50',
        'overlay-scrim-background': '#A7D9C5',
        'overlay-scrim-opacity': 0.5,
        'shadow-key-umbra-opacity': 'rgba(var(--v-theme-on-surface), 0.08)',
        'shadow-key-penumbra-opacity': 'rgba(var(--v-theme-on-surface), 0.05)',
        'shadow-key-ambient-opacity': 'rgba(var(--v-theme-on-surface), 0.03)',
      },
    };
  }
  return {
    dark: true,
    colors: {
      background: '#1B5E20',
      surface: '#2E7D32',
      'surface-variant': '#388E3C',
      'on-surface-variant': '#A5D6A7',
      primary: chainStore.current?.themeColor || '#66BB6A', // Dark green primary
      'primary-darken-1': '#388E3C',
      secondary: '#81C784',
      'secondary-darken-1': '#4CAF50',
      error: '#EF9A9A',
      info: '#90CAF9',
      success: '#66BB6A',
      warning: '#FFCC80',
      'on-primary': '#FFFFFF',
      'on-secondary': '#FFFFFF',
      'on-success': '#FFFFFF',
      'on-info': '#FFFFFF',
      'on-warning': '#FFFFFF',
      'on-background': '#E8F5E9',
      'on-surface': '#E8F5E9',
      'perfect-scrollbar-thumb': '#66BB6A',
      'snackbar-background': '#2E7D32',
      'on-snackbar-background': '#E8F5E9',
      'tooltip-background': '#43A047',
      'alert-background': '#388E3C',
      'grey-50': '#2E7D32',
      'grey-100': '#388E3C',
      'grey-200': '#43A047',
      'grey-300': '#4CAF50',
      'grey-400': '#66BB6A',
      'grey-500': '#81C784',
      'grey-600': '#A5D6A7',
      'grey-700': '#C8E6C9',
      'grey-800': '#E8F5E9',
      'grey-900': '#F1FDF6',
      'on-primary-darken-1': '#FFFFFF',
      'on-secondary-darken-1': '#FFFFFF',
      'on-error': '#FFFFFF',
      'on-perfect-scrollbar-thumb': '#FFFFFF',
      'on-tooltip-background': '#FFFFFF',
      'on-alert-background': '#FFFFFF',
      'on-grey-50': '#FFFFFF',
      'on-grey-100': '#FFFFFF',
      'on-grey-200': '#FFFFFF',
      'on-grey-300': '#FFFFFF',
      'on-grey-400': '#FFFFFF',
      'on-grey-500': '#FFFFFF',
      'on-grey-600': '#000000',
      'on-grey-700': '#000000',
      'on-grey-800': '#000000',
      'on-grey-900': '#000000',
    },
    variables: {
      'border-color': '#A5D6A7',
      'border-opacity': 0.12,
      'high-emphasis-opacity': 0.87,
      'medium-emphasis-opacity': 0.6,
      'disabled-opacity': 0.38,
      'idle-opacity': 0.1,
      'hover-opacity': 0.05,
      'focus-opacity': 0.12,
      'selected-opacity': 0.08,
      'activated-opacity': 0.12,
      'pressed-opacity': 0.16,
      'dragged-opacity': 0.08,
      'theme-kbd': '#66BB6A',
      'theme-on-kbd': '#FFFFFF',
      'theme-code': '#2E7D32',
      'theme-on-code': '#E8F5E9',
      'code-color': '#81C784',
      'overlay-scrim-background': '#1B5E20',
      'overlay-scrim-opacity': 0.6,
      'shadow-key-umbra-opacity': 'rgba(20, 21, 33, 0.08)',
      'shadow-key-penumbra-opacity': 'rgba(20, 21, 33, 0.05)',
      'shadow-key-ambient-opacity': 'rgba(20, 21, 33, 0.03)',
    },
  };
};
